additional_cargo_args = ["--all-features"]
exclude_re = [
  # Coverage of debug & display functions is not relevant
  "impl Debug",
  "impl Display",
  # Replacing + with * makes no logical difference here
  "src/olm/messages/message\\.rs.*replace \\+ with \\* in <impl TryFrom for Message>::try_from",
  # Due to the bit shifting | and ^ are equivalent here
  "replace \\| with \\^ in SasBytes::bytes_to_decimal",
  # Drop implementations perform zeroisation which cannot be tested in Rust
  "impl Drop",
  # These cause olm/account tests to hang
  "RemoteChainKey::chain_index",
  "RemoteChainKey::advance",
  # The constant value can't really be tested
  "src/olm/account/one_time_keys\\.rs.*replace \\* with \\+$",
]
